#!/bin/bash

year=$1

cp -r template ${year}
(
	cd ${year}

	sed -e "s/AoCxxxx/AoC${year}/g" AoCxxxx.hs > AoC${year}.hs
	rm AoCxxxx.hs

	mv AoCxxxx AoC${year}
	(
		cd AoC${year}

		for day in $(seq 1 25)
		do
			daystr=Day$(printf "%02d" ${day})
			cp -r Dayxx ${daystr}
			sed -e "s/AoCxxxx/AoC${year}/g" -e "s/Dayxx/${daystr}/" Dayxx.hs > ${daystr}.hs
		done
		rm -rf Dayxx Dayxx.hs
	)

)

mv ${year}/* src/
rmdir ${year}

(
	cd src
	cp Main.hs Main${year}.hs
	grep -- "-- TEMPLATE " Main${year}.hs | while read template
	do
		rendered="${template//xxxx/${year}}"
		rendered="${rendered/-- TEMPLATE /}"
		sed -e "s/${template}/${rendered}\n${template}/g" Main${year}.hs > Main${year}.hs.sed
		mv Main${year}.hs.sed Main${year}.hs
	done
	mv Main${year}.hs Main.hs
)

