#!/bin/bash

function show_help () {
  echo "$0 [-h] [-t] <year>/<day> [part]

-h            help (this)

-p            Don't run tests

-t            Only run tests

-c            Only compile
  "
}

TEST=true
PROD=true
while getopts "htcp" opt; do
  case "$opt" in
  h|\?)
    show_help
    exit 0
    ;;
  p)
    TEST=false
    ;;
  t)
    PROD=false
    ;;
  c)
    TEST=false
    PROD=false
    ;;
  :)
    echo "Option -$OPTARG requires an argument." >&2
    exit 1
    ;;
  esac
done

shift $(($OPTIND - 1))
dir="$1"
RUNARGS="--yeardaystr=${dir}"
part="$2"
if [ -n "$part" ]
then
	RUNARGS="${RUNARGS} --part=${part}"
fi

cabal new-build aoc
if [ $? -gt 0 ]
then
	exit 1
fi

if $TEST
then
	for testinput in $dir/testinput*
	do
		echo Running $testinput
		time cabal new-run aoc -- $RUNARGS < $testinput
	done
fi

if $PROD
then
	echo Running actual input
	time cabal new-run aoc -- $RUNARGS < $dir/input
fi
