#!/bin/bash

function show_help () {
  echo "$0 [-h] [-t] <year>/<day>-<part>

-h            help (this)

-t            Only run tests

-c            Only compile

-d            Run profiling, debugging
  "
}

TEST=true
PROD=true
while getopts "htdc" opt; do
  case "$opt" in
  h|\?)
    show_help
    exit 0
    ;;
  t)
    PROD=false
    ;;
  c)
    TEST=false
    PROD=false
    ;;
  d)
    GHCOPTS="-prof -fprof-auto -fprof-cafs"
    RUNOPTS="+RTS -xc"
    ;;
  :)
    echo "Option -$OPTARG requires an argument." >&2
    exit 1
    ;;
  esac
done

shift $(($OPTIND - 1))
dir="$@"

cd $dir

ghc Advent $GHCOPTS || exit 1

if $TEST
then
	for testinput in testinput*
	do
		time ./Advent $RUNOPTS < $testinput
	done
fi

if $PROD
then
  time ./Advent $RUNOPTS < input
fi
